name: Deploy ANFC App

on:
  push:
    branches:
      - main # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Run SSH Command
        run: |
          sshpass -p "${{ secrets.PRODUCTION_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.PRODUCTION_SSH_PORT }} ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_SSH_HOST }} << 'EOF'
            cd app.alfaandfriends.com || { echo "Failed to change directory"; exit 1; }
            git pull origin main || { echo "Git pull failed"; exit 1; }
            npm install || { echo "npm install failed"; exit 1; }
            npm run build || { echo "npm run build failed"; exit 1; }
            composer install || { echo "composer install failed"; exit 1; }
            php artisan optimize:clear || { echo "php artisan optimize:clear failed"; exit 1; }
          EOF

