name: Deploy ANFC App

on:
  push:
    branches:
      - main # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Run SSH Command
        run: |
          sshpass -p "${{ secrets.PRODUCTION_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.PRODUCTION_SSH_PORT }} ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_SSH_HOST }} "
            cd app.alfaandfriends.com
            git pull origin main
            composer install
            npm install install
            npm run build
            php artisan optimize:clear
          "

      # - name: Deploy to Production
      #   # if: github.ref == 'refs/heads/main'
      #   uses: appleboy/ssh-action@v1.2.0
      #   with:
      #     host: ${{ secrets.PRODUCTION_SSH_HOST }}
      #     port: ${{ secrets.PRODUCTION_SSH_PORT }}
      #     username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
      #     key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.PRODUCTION_SSH_PASSPHRASE }}
      #     script: |
      #       cd app.alfaandfriends.com
      #       git pull origin main
      #       composer install
      #       npm run build
      #       php artisan optimize:clear

